# Default values for nginx-suave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

frontendImage:
  name: nginx
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

backendImage:
  name: littlesuave
  repository: dcurylo/littlesuave
  tag: latest
  pullPolicy: IfNotPresent

frontendService:
  name: nginx
  type: NodePort
  port: 80

ingress:
  enabled: false
