apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "nginx-suave.fullname" . }}
  labels:
    app: {{ template "nginx-suave.fullname" . }}
    chart: {{ template "nginx-suave.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "nginx-suave.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "nginx-suave.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.backendImage.name }}
          image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}"
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          ports:
            - name: apphttp
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: apphttp
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: apphttp
            initialDelaySeconds: 5
        - name: {{ .Chart.Name }}-{{ .Values.frontendImage.name }}
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/
            - name: nginx-content
              mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap: 
          name: {{ template "nginx-suave.fullname" . }}-conf
      - name: nginx-content
        configMap: 
          name: {{ template "nginx-suave.fullname" . }}-content
