apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-suave.fullname" . }}
  labels:
    app: {{ template "nginx-suave.fullname" . }}
    chart: {{ template "nginx-suave.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontendService.type }}
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.port }}
      protocol: TCP
      name: {{ .Values.frontendService.name }}
  selector:
    app: {{ template "nginx-suave.fullname" . }}
    release: {{ .Release.Name }}
